// =====================================================================
// PRODUCT SEED DATA
// ---------------------------------------------------------------------
// 50+ realistic products across 6 categories. To add new products:
//   1. Append entries to the `products` array below
//   2. Run: bun run scripts/seed.ts
// To replace placeholder data with real catalog: edit this file.
// =====================================================================

export type SeedProduct = {
  name: string;
  slug: string;
  sku: string;
  description: string;
  shortDescription: string;
  price: number;
  salePrice?: number | null;
  currency?: string;
  thumbnail: string;
  images: string[];
  categorySlug: string;
  brandName?: string;
  sizes?: string[];
  colors?: string[];
  stock: number;
  tags?: string[];
  featured?: boolean;
  bestSeller?: boolean;
  newArrival?: boolean;
  rating?: number;
  reviewCount?: number;
  specifications?: Record<string, string>;
  shippingInfo?: string;
};

export type SeedCategory = {
  name: string;
  slug: string;
  description: string;
  image: string;
};

export type SeedBrand = {
  name: string;
  slug: string;
};

// ---------------------------------------------------------------------
// CATEGORIES
// ---------------------------------------------------------------------
export const categories: SeedCategory[] = [
  {
    name: "Electronics",
    slug: "electronics",
    description: "Headphones, speakers, wearables, and accessories that keep you connected and entertained.",
    image: "https://images.unsplash.com/photo-1498049794561-1f525d45c48b?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Fashion",
    slug: "fashion",
    description: "Thoughtfully designed apparel and footwear for everyday wear, work, and weekends.",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Home & Living",
    slug: "home-living",
    description: "Furniture, kitchenware, and décor that turn a house into a home.",
    image: "https://images.unsplash.com/photo-1493663280992-2004daab9dc7?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Beauty & Care",
    slug: "beauty-care",
    description: "Skincare, fragrance, and grooming products made for daily rituals.",
    image: "https://images.unsplash.com/photo-1596462500400-2bef5f5e5b91?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Gear and apparel for athletes, adventurers, and weekend warriors.",
    image: "https://images.unsplash.com/photo-1517649763962-0c70023b4e05?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Accessories",
    slug: "accessories",
    description: "Bags, watches, and the small details that complete the look.",
    image: "https://images.unsplash.com/photo-1521369772785-1ca6460d363b?auto=format&fit=crop&w=800&q=80",
  },
];

// ---------------------------------------------------------------------
// BRANDS
// ---------------------------------------------------------------------
export const brands: SeedBrand[] = [
  { name: "Lumio", slug: "lumio" },
  { name: "Northwind", slug: "northwind" },
  { name: "Kestrel", slug: "kestrel" },
  { name: "Marisol", slug: "marisol" },
  { name: "Atelier 9", slug: "atelier-9" },
  { name: "Field & Co", slug: "field-and-co" },
  { name: "Verde", slug: "verde" },
  { name: "Halden", slug: "halden" },
];

// ---------------------------------------------------------------------
// PRODUCTS — 58 across categories
// ---------------------------------------------------------------------
export const products: SeedProduct[] = [
  // ---------------- ELECTRONICS (12) ----------------
  {
    name: "Aria Wireless Noise-Cancelling Headphones",
    slug: "aria-wireless-noise-cancelling-headphones",
    sku: "ELE-ARIA-001",
    description: "Aria headphones deliver studio-grade sound with adaptive noise cancellation that adjusts to your environment. Memory-foam ear cushions provide all-day comfort, while the 40-hour battery keeps the music going across long-haul flights. USB-C fast charging gives 5 hours of playback in 10 minutes.",
    shortDescription: "Adaptive ANC, 40-hour battery, and studio-grade sound in a featherlight frame.",
    price: 249.00,
    salePrice: 199.00,
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5d4d6c2a1f6f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5d4d6c2a1f6f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583394838443-86d4d839e5e5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1487217573587-3dbf869c4c3f?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Lumio",
    colors: ["Black", "Silver", "Navy"],
    stock: 80,
    tags: ["audio", "wireless", "anc", "bestseller"],
    featured: true,
    bestSeller: true,
    rating: 4.7,
    reviewCount: 312,
    specifications: { "Driver": "40mm dynamic", "Battery": "40 hours", "Charging": "USB-C", "Weight": "248 g", "Bluetooth": "5.3" },
    shippingInfo: "Ships in 1-2 business days. Free standard shipping on orders over $50.",
  },
  {
    name: "Pulse True Wireless Earbuds",
    slug: "pulse-true-wireless-earbuds",
    sku: "ELE-PULSE-002",
    description: "Pulse earbuds deliver crisp highs and tight bass in a pocketable case. IPX5 water resistance means they survive workouts and rainy commutes, and touch controls keep your phone in your pocket.",
    shortDescription: "Pocket-sized earbuds with IPX5 resistance and 24-hour total battery.",
    price: 89.00,
    thumbnail: "https://images.unsplash.com/photo-1590658268062-06d004fc1d2c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1590658268062-06d004fc1d2c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1572569511254-d8f925fe7c4c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Lumio",
    colors: ["White", "Black"],
    stock: 200,
    tags: ["audio", "earbuds", "wireless"],
    bestSeller: true,
    rating: 4.5,
    reviewCount: 187,
    specifications: { "Driver": "11mm", "Battery": "6h + 18h case", "Water rating": "IPX5", "Bluetooth": "5.2" },
    shippingInfo: "Ships in 1-2 business days.",
  },
  {
    name: "Vista 27-inch 4K UHD Monitor",
    slug: "vista-27-4k-uhd-monitor",
    sku: "ELE-VISTA-003",
    description: "A 27-inch 4K IPS panel with 99% sRGB coverage, the Vista monitor brings photos, video, and spreadsheets to life with crisp detail and accurate color. A near-frameless design keeps your focus on the screen, and the height-adjustable stand helps you find the perfect angle.",
    shortDescription: "27-inch 4K IPS panel with 99% sRGB and an ergonomic stand.",
    price: 379.00,
    salePrice: 329.00,
    thumbnail: "https://images.unsplash.com/photo-1527443224154-f55865847fef?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1527443224154-f55865847fef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1593642632823-98b1f32c0a9c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Kestrel",
    stock: 45,
    tags: ["display", "4k", "office"],
    featured: true,
    rating: 4.6,
    reviewCount: 89,
    specifications: { "Panel": "IPS", "Resolution": "3840 x 2160", "Refresh": "60 Hz", "Ports": "HDMI 2.0 x 2, DisplayPort, USB-C" },
    shippingInfo: "Ships in 2-4 business days.",
  },
  {
    name: "Nimbus Mechanical Keyboard",
    slug: "nimbus-mechanical-keyboard",
    sku: "ELE-NIMB-004",
    description: "A hot-swappable mechanical keyboard with brown tactile switches, PBT keycaps, and a solid aluminum frame. Wireless, USB-C, or Bluetooth — pick your weapon. RGB backlight that won't blind you at midnight.",
    shortDescription: "Hot-swappable mechanical keyboard with PBT keycaps and aluminum frame.",
    price: 129.00,
    thumbnail: "https://images.unsplash.com/photo-1587829748621-9bb0e6cb0a82?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1587829748621-9bb0e6cb0a82?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618384887929-5ec5b9a0f6d6?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Halden",
    colors: ["Black", "White"],
    stock: 120,
    tags: ["keyboard", "mechanical", "wireless"],
    newArrival: true,
    rating: 4.8,
    reviewCount: 156,
    specifications: { "Switches": "Brown tactile", "Keycaps": "PBT", "Connectivity": "BT 5.1 / USB-C / 2.4GHz", "Battery": "240 hours" },
  },
  {
    name: "Cobalt Smartwatch Series 5",
    slug: "cobalt-smartwatch-series-5",
    sku: "ELE-COBA-005",
    description: "A stainless-steel smartwatch with health tracking, GPS, and a 7-day battery. Notifications, contactless payments, and onboard music keep your phone in your pocket. Water resistant to 5 ATM.",
    shortDescription: "Health-tracking smartwatch with GPS, contactless pay, and 7-day battery.",
    price: 219.00,
    salePrice: 179.00,
    thumbnail: "https://images.unsplash.com/photo-1523275335684-3c7d2c2c2d2d?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-3c7d2c2c2d2d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1579586337277-82d8738d2f9b?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Lumio",
    colors: ["Graphite", "Silver", "Gold"],
    stock: 95,
    tags: ["wearable", "smartwatch", "fitness"],
    bestSeller: true,
    rating: 4.4,
    reviewCount: 224,
    specifications: { "Display": "1.4 inch AMOLED", "Battery": "7 days", "Water rating": "5 ATM", "GPS": "Dual-band" },
  },
  {
    name: "Echo Portable Bluetooth Speaker",
    slug: "echo-portable-bluetooth-speaker",
    sku: "ELE-ECHO-006",
    description: "Big sound in a small package. The Echo speaker packs a 30W driver, 18-hour battery, and IP67 dust/water resistance. Pair two for stereo sound.",
    shortDescription: "30W portable speaker with IP67 rating and 18-hour battery.",
    price: 79.00,
    thumbnail: "https://images.unsplash.com/photo-1608083158660-44b7d5b58e9e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1608083158660-44b7d5b58e9e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1545458927-6d5f5b5d0e7c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Lumio",
    colors: ["Black", "Olive", "Coral"],
    stock: 150,
    tags: ["audio", "speaker", "portable"],
    rating: 4.5,
    reviewCount: 98,
    specifications: { "Output": "30W", "Battery": "18 hours", "Water rating": "IP67", "Bluetooth": "5.3" },
  },
  {
    name: "Lumen Desk Lamp with Wireless Charging",
    slug: "lumen-desk-lamp-wireless-charging",
    sku: "ELE-LUMEN-007",
    description: "A minimalist LED desk lamp with built-in 15W Qi wireless charging. Three color temperatures and five brightness levels for any time of day. Eye-care flicker-free technology.",
    shortDescription: "LED desk lamp with 15W wireless charging and flicker-free light.",
    price: 69.00,
    thumbnail: "https://images.unsplash.com/photo-1507473884508-5d671ab8c0c7?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1507473884508-5d671ab8c0c7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1517991109296-8d9b1c8e6b1c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Halden",
    colors: ["White", "Black"],
    stock: 70,
    tags: ["lighting", "office", "wireless-charging"],
    newArrival: true,
    rating: 4.6,
    reviewCount: 64,
    specifications: { "Power": "15W Qi", "Color temp": "2700K-6500K", "Brightness": "5 levels" },
  },
  {
    name: "Quartet 4K Webcam",
    slug: "quartet-4k-webcam",
    sku: "ELE-QUAR-008",
    description: "Stream and meet in 4K. The Quartet webcam features a Sony sensor, HDR, dual-mic with noise reduction, and a magnetic privacy cover. Plug-and-play over USB-C.",
    shortDescription: "4K HDR webcam with dual noise-cancelling mics.",
    price: 99.00,
    thumbnail: "https://images.unsplash.com/photo-1587825140144-85c2b5b1c8e7?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1587825140144-85c2b5b1c8e7?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Kestrel",
    stock: 60,
    tags: ["webcam", "streaming", "office"],
    rating: 4.3,
    reviewCount: 42,
    specifications: { "Sensor": "Sony 1/2.5 inch", "Resolution": "4K 30fps", "Field of view": "78 deg", "Microphones": "Dual stereo" },
  },
  {
    name: "Aer Compact Phone Gimbal",
    slug: "aer-compact-phone-gimbal",
    sku: "ELE-AER-009",
    description: "Capture buttery-smooth video with this three-axis phone gimbal. ActiveTrack keeps subjects centered, and the foldable design fits in a coat pocket.",
    shortDescription: "Three-axis smartphone gimbal with ActiveTrack subject tracking.",
    price: 119.00,
    thumbnail: "https://images.unsplash.com/photo-1605981648555-d6a7d62b0d6f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1605981648555-d6a7d62b0d6f?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Kestrel",
    stock: 35,
    tags: ["photography", "gimbal", "video"],
    rating: 4.4,
    reviewCount: 51,
    specifications: { "Axes": "3", "Payload": "280 g", "Battery": "12 hours", "Connectivity": "BT 5.0" },
  },
  {
    name: "Surge 65W GaN Charger",
    slug: "surge-65w-gan-charger",
    sku: "ELE-SURGE-010",
    description: "One charger to rule them all. The Surge GaN charger powers laptops, phones, and tablets with 65W total output across two USB-C ports and one USB-A. Smaller than a deck of cards.",
    shortDescription: "65W GaN charger with 2x USB-C and 1x USB-A.",
    price: 49.00,
    thumbnail: "https://images.unsplash.com/photo-1583394838443-86d4d839e5e5?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583394838443-86d4d839e5e5?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Halden",
    stock: 220,
    tags: ["charging", "accessories"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 178,
    specifications: { "Output": "65W total", "Ports": "2x USB-C, 1x USB-A", "Technology": "GaN II" },
  },
  {
    name: "Trace Bluetooth Tracker (4-Pack)",
    slug: "trace-bluetooth-tracker-4-pack",
    sku: "ELE-TRACE-011",
    description: "Never lose your keys again. Trace trackers ping your phone when you can't find them, and a global network helps locate items far from home. Loud ringer, water resistant, 1-year battery.",
    shortDescription: "4-pack of Bluetooth item trackers with loud ringer and 1-year battery.",
    price: 39.00,
    thumbnail: "https://images.unsplash.com/photo-1558366128-d6d8378d6f8c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558366128-d6d8378d6f8c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Halden",
    stock: 180,
    tags: ["tracker", "accessories"],
    rating: 4.2,
    reviewCount: 134,
    specifications: { "Range": "60 m", "Battery": "1 year (replaceable)", "Water rating": "IP67" },
  },
  {
    name: "Nova Smart Home Hub",
    slug: "nova-smart-home-hub",
    sku: "ELE-NOVA-012",
    description: "Control your lights, thermostat, locks, and speakers from one 7-inch touchscreen hub. Works with the major smart home protocols. Privacy-first design with on-device processing.",
    shortDescription: "7-inch smart home hub with multi-protocol support.",
    price: 149.00,
    thumbnail: "https://images.unsplash.com/photo-1558002038-1b90e5cd9a3e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558002038-1b90e5cd9a3e?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "electronics",
    brandName: "Lumio",
    stock: 55,
    tags: ["smart-home", "hub"],
    newArrival: true,
    rating: 4.3,
    reviewCount: 28,
    specifications: { "Display": "7-inch touchscreen", "Protocols": "Matter, Zigbee, Z-Wave", "Power": "AC" },
  },

  // ---------------- FASHION (10) ----------------
  {
    name: "Everyday Cotton Crewneck Tee",
    slug: "everyday-cotton-crewneck-tee",
    sku: "FAS-TEE-001",
    description: "A wardrobe staple, ethically made from 100% organic combed cotton with a relaxed crew neckline. Pre-shrunk for a true-to-size fit wash after wash.",
    shortDescription: "Soft organic cotton tee in a relaxed fit.",
    price: 28.00,
    thumbnail: "https://images.unsplash.com/photo-1521572163474-6864f9cf1a2a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf1a2a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503341504253-dff481a3e8f9?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Marisol",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Heather Grey", "Navy", "Olive"],
    stock: 500,
    tags: ["tees", "basics", "cotton"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 412,
    specifications: { "Material": "100% organic cotton", "Fit": "Relaxed", "Weight": "180 gsm" },
  },
  {
    name: "Heritage Selvedge Denim Jeans",
    slug: "heritage-selvedge-denim-jeans",
    sku: "FAS-JEAN-002",
    description: "Japanese selvedge denim with a slim-straight leg and a button fly. Mid-rise, durable enough for daily wear, and built to fade beautifully over time.",
    shortDescription: "Slim-straight Japanese selvedge denim with button fly.",
    price: 128.00,
    salePrice: 98.00,
    thumbnail: "https://images.unsplash.com/photo-1542272604-92d6d5c7a9d4?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1542272604-92d6d5c7a9d4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1604176841010-3eda1d5a3b6b?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Northwind",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Indigo", "Washed Blue", "Black"],
    stock: 180,
    tags: ["denim", "jeans", "selvedge"],
    featured: true,
    rating: 4.7,
    reviewCount: 187,
    specifications: { "Material": "14 oz selvedge denim", "Fit": "Slim-straight", "Fly": "Button" },
  },
  {
    name: "Merino Wool Crewneck Sweater",
    slug: "merino-wool-crewneck-sweater",
    sku: "FAS-SWE-003",
    description: "Lightweight 100% extra-fine merino wool that breathes in summer and insulates in winter. Naturally odor-resistant. Looks sharp layered or on its own.",
    shortDescription: "Extra-fine merino crewneck for year-round layering.",
    price: 89.00,
    thumbnail: "https://images.unsplash.com/photo-1434389677295-8a1a7c91f4c8?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1434389677295-8a1a7c91f4c8?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Northwind",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Camel", "Forest", "Burgundy"],
    stock: 120,
    tags: ["sweater", "merino", "knitwear"],
    rating: 4.6,
    reviewCount: 76,
    specifications: { "Material": "100% merino wool", "Weight": "200 gsm", "Care": "Machine wash cold" },
  },
  {
    name: "Waxed Canvas Field Jacket",
    slug: "waxed-canvas-field-jacket",
    sku: "FAS-JKT-004",
    description: "A modern take on a classic. British waxed cotton canvas sheds light rain, while the corduroy collar and tartan lining bring timeless style. Four pockets, two-way zip, and an adjustable waist.",
    shortDescription: "British waxed cotton canvas with corduroy collar.",
    price: 189.00,
    thumbnail: "https://images.unsplash.com/photo-1591047139832-9b1d6c5f6c8a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1591047139832-9b1d6c5f6c8a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Field & Co",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive", "Black", "Brown"],
    stock: 75,
    tags: ["jacket", "outerwear", "waxed"],
    featured: true,
    newArrival: true,
    rating: 4.8,
    reviewCount: 53,
    specifications: { "Material": "Waxed cotton canvas", "Lining": "Tartan", "Pockets": "4" },
  },
  {
    name: "Linen Summer Shirt",
    slug: "linen-summer-shirt",
    sku: "FAS-SHI-005",
    description: "Breathable 100% European linen with a relaxed fit. Perfect for warm days — looks just as good over a tee as it does buttoned up.",
    shortDescription: "Breathable linen shirt in a relaxed fit.",
    price: 65.00,
    thumbnail: "https://images.unsplash.com/photo-1602810318371-4d4d8e3c0c2d?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1602810318371-4d4d8e3c0c2d?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Marisol",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sand", "Sky Blue", "Sage"],
    stock: 130,
    tags: ["shirt", "linen", "summer"],
    rating: 4.5,
    reviewCount: 88,
    specifications: { "Material": "100% European linen", "Fit": "Relaxed" },
  },
  {
    name: "Trail Running Sneakers",
    slug: "trail-running-sneakers",
    sku: "FAS-SNK-006",
    description: "Aggressive lugged outsole for grip on loose terrain, a rock plate for underfoot protection, and a breathable mesh upper. Lightweight enough for daily training, durable enough for weekend ultras.",
    shortDescription: "Lightweight trail runners with lugged grip and rock plate.",
    price: 139.00,
    salePrice: 109.00,
    thumbnail: "https://images.unsplash.com/photo-1542291026-7c2c6e8f5b9c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7c2c6e8f5b9c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606107557125-3cb3c4d0c4e3?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Kestrel",
    sizes: ["7", "8", "9", "10", "11", "12", "13"],
    colors: ["Black/Lime", "Slate/Orange", "Sand/Brown"],
    stock: 200,
    tags: ["sneakers", "running", "trail"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 243,
    specifications: { "Upper": "Engineered mesh", "Midsole": "EVA foam", "Outsole": "Rubber 4mm lug", "Drop": "8 mm" },
  },
  {
    name: "Cashmere Blend Scarf",
    slug: "cashmere-blend-scarf",
    sku: "FAS-SCF-007",
    description: "Sumptuously soft 70% cashmere / 30% wool scarf in a generous size that wraps without bulk. Fringed ends. A timeless cold-weather essential.",
    shortDescription: "70% cashmere / 30% wool scarf with fringed ends.",
    price: 75.00,
    thumbnail: "https://images.unsplash.com/photo-1604061986769-3b2d3e6c7b8e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1604061986769-3b2d3e6c7b8e?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Marisol",
    colors: ["Camel", "Charcoal", "Burgundy", "Forest"],
    stock: 90,
    tags: ["accessory", "scarf", "winter"],
    rating: 4.7,
    reviewCount: 64,
    specifications: { "Material": "70% cashmere, 30% wool", "Size": "180 x 30 cm" },
  },
  {
    name: "Tailored Wool Trousers",
    slug: "tailored-wool-trousers",
    sku: "FAS-TRO-008",
    description: "A modern slim-straight trouser cut from Italian wool blend with a touch of stretch. Side adjusters instead of belt loops give a clean, tailored line.",
    shortDescription: "Italian wool-blend trousers with side adjusters.",
    price: 119.00,
    thumbnail: "https://images.unsplash.com/photo-1473966968420-9d5c0b3a3e3f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1473966968420-9d5c0b3a3e3f?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Atelier 9",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Charcoal", "Navy", "Stone"],
    stock: 110,
    tags: ["trousers", "formal", "wool"],
    rating: 4.5,
    reviewCount: 47,
    specifications: { "Material": "98% wool, 2% elastane", "Fit": "Slim-straight" },
  },
  {
    name: "Pleated Midi Skirt",
    slug: "pleated-midi-skirt",
    sku: "FAS-SKT-009",
    description: "A flowing pleated midi skirt cut from recycled polyester that moves beautifully. Elastic waist for all-day comfort. Pairs with everything from a tee to a blouse.",
    shortDescription: "Pleated midi skirt with elastic waist and recycled fabric.",
    price: 69.00,
    thumbnail: "https://images.unsplash.com/photo-15834966616632-9d8b5c5e8b3e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-15834966616632-9d8b5c5e8b3e?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Marisol",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Wine", "Sage", "Cream"],
    stock: 100,
    tags: ["skirt", "midi", "pleated"],
    newArrival: true,
    rating: 4.4,
    reviewCount: 39,
    specifications: { "Material": "100% recycled polyester", "Length": "Midi" },
  },
  {
    name: "Pima Henley Long Sleeve",
    slug: "pima-henley-long-sleeve",
    sku: "FAS-HEN-010",
    description: "A buttery-soft Pima cotton henley with a three-button placket. Pre-washed for that lived-in feel. Layered or alone, it just works.",
    shortDescription: "Pima cotton henley with three-button placket.",
    price: 49.00,
    thumbnail: "https://images.unsplash.com/photo-1622445315588-3c8f3c8e1d6e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1622445315588-3c8f3c8e1d6e?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "fashion",
    brandName: "Northwind",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Oatmeal", "Black", "Forest", "Wine"],
    stock: 160,
    tags: ["henley", "longsleeve", "basics"],
    rating: 4.6,
    reviewCount: 92,
    specifications: { "Material": "100% Pima cotton", "Fit": "Regular" },
  },

  // ---------------- HOME & LIVING (10) ----------------
  {
    name: "Linen Duvet Cover Set",
    slug: "linen-duvet-cover-set",
    sku: "HOM-LIN-001",
    description: "Pre-washed European flax linen duvet cover with a relaxed, lived-in texture. Breathable, temperature-regulating, and gets softer with every wash. Includes duvet cover and two pillow shams.",
    shortDescription: "Pre-washed flax linen duvet cover set with two shams.",
    price: 159.00,
    salePrice: 129.00,
    thumbnail: "https://images.unsplash.com/photo-1522771739844-6ce8d7d8a5c9?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1522771739844-6ce8d7d8a5c9?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Marisol",
    colors: ["Natural", "Clay", "Slate", "Sage"],
    stock: 80,
    tags: ["bedding", "linen", "duvet"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 156,
    specifications: { "Material": "100% European flax linen", "Includes": "Duvet cover + 2 shams", "Care": "Machine wash cold" },
  },
  {
    name: "Stoneware Dinner Plate Set (4)",
    slug: "stoneware-dinner-plate-set-4",
    sku: "HOM-STO-002",
    description: "Hand-finished stoneware dinner plates with a speckled glaze that gives each piece its own character. Dishwasher and microwave safe. Set of four.",
    shortDescription: "Speckled stoneware dinner plates, set of 4.",
    price: 89.00,
    thumbnail: "https://images.unsplash.com/photo-1530049576056-9b0c5f1c8e9a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1530049576056-9b0c5f1c8e9a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Atelier 9",
    colors: ["Sand", "Charcoal", "Sage"],
    stock: 100,
    tags: ["dinnerware", "plates", "stoneware"],
    rating: 4.6,
    reviewCount: 73,
    specifications: { "Material": "Stoneware", "Set": "4 plates", "Diameter": "27 cm" },
  },
  {
    name: "Mid-Century Lounge Chair",
    slug: "mid-century-lounge-chair",
    sku: "HOM-CHR-003",
    description: "Solid oak frame with a molded plywood shell upholstered in top-grain leather. Inspired by 1950s design and built for daily use. Some assembly required.",
    shortDescription: "Solid oak frame with top-grain leather upholstery.",
    price: 549.00,
    salePrice: 449.00,
    thumbnail: "https://images.unsplash.com/photo-1592079802870-9b6d8c7c8e3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1592079802870-9b6d8c7c8e3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Atelier 9",
    colors: ["Tan Leather", "Black Leather", "Olive Wool"],
    stock: 25,
    tags: ["furniture", "chair", "lounge"],
    featured: true,
    rating: 4.8,
    reviewCount: 41,
    specifications: { "Frame": "Solid oak", "Upholstery": "Top-grain leather", "Dimensions": "75 x 80 x 80 cm" },
    shippingInfo: "White-glove delivery in 5-10 business days.",
  },
  {
    name: "Ceramic Pour-Over Coffee Set",
    slug: "ceramic-pour-over-coffee-set",
    sku: "HOM-COF-004",
    description: "A complete pour-over set including a ceramic dripper, glass carafe, and 20 paper filters. The dripper's ribbed interior promotes even extraction for a clean, balanced cup.",
    shortDescription: "Pour-over coffee set: ceramic dripper, carafe, and filters.",
    price: 59.00,
    thumbnail: "https://images.unsplash.com/photo-1495474472287-4d9d56d4647f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1495474472287-4d9d56d4647f?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Halden",
    colors: ["White", "Black", "Sand"],
    stock: 130,
    tags: ["coffee", "kitchen", "pour-over"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 211,
    specifications: { "Includes": "Dripper, carafe, 20 filters", "Capacity": "600 ml" },
  },
  {
    name: "Wool Area Rug 5x8",
    slug: "wool-area-rug-5x8",
    sku: "HOM-RUG-005",
    description: "Hand-tufted wool area rug with a subtle geometric pattern. Durable enough for high-traffic areas and naturally stain-resistant. Cotton backing with stitched edges.",
    shortDescription: "Hand-tufted wool rug, 5x8 ft, geometric pattern.",
    price: 299.00,
    salePrice: 249.00,
    thumbnail: "https://images.unsplash.com/photo-1600166898150-9d8b5c5e3c0a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1600166898150-9d8b5c5e3c0a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Field & Co",
    colors: ["Natural", "Charcoal", "Rust"],
    stock: 40,
    tags: ["rug", "wool", "decor"],
    rating: 4.5,
    reviewCount: 58,
    specifications: { "Material": "100% wool", "Size": "5 x 8 ft", "Backing": "Cotton" },
    shippingInfo: "Ships in 3-5 business days.",
  },
  {
    name: "Soy Wax Scented Candle",
    slug: "soy-wax-scented-candle",
    sku: "HOM-CND-006",
    description: "Hand-poured soy wax candle with a cotton wick. Cedarwood and smoke scent with notes of leather and amber. 50-hour burn time. Reusable glass vessel.",
    shortDescription: "Cedarwood and smoke soy candle, 50-hour burn.",
    price: 32.00,
    thumbnail: "https://images.unsplash.com/photo-1602874801006-7c0c1c3a3b6a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1602874801006-7c0c1c3a3b6a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Verde",
    colors: ["Cedarwood & Smoke", "Fig & Cassis", "Linen & Sea Salt"],
    stock: 220,
    tags: ["candle", "decor", "fragrance"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 134,
    specifications: { "Wax": "Soy", "Burn time": "50 hours", "Weight": "280 g" },
  },
  {
    name: "Bamboo Cutting Board Set (3)",
    slug: "bamboo-cutting-board-set-3",
    sku: "HOM-BAM-007",
    description: "Three sustainable bamboo cutting boards in graduated sizes. Naturally antibacterial, gentle on knives, and built to last. Built-in hanging hole.",
    shortDescription: "Three graduated bamboo cutting boards.",
    price: 39.00,
    thumbnail: "https://images.unsplash.com/photo-1559925234-57c8e6e0c6f0?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1559925234-57c8e6e0c6f0?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Halden",
    stock: 180,
    tags: ["kitchen", "bamboo", "cutting-board"],
    rating: 4.7,
    reviewCount: 198,
    specifications: { "Material": "Bamboo", "Set": "3 boards (large, medium, small)" },
  },
  {
    name: "Glass Water Carafe with Wood Lid",
    slug: "glass-water-carafe-with-wood-lid",
    sku: "HOM-CAR-008",
    description: "Hand-blown glass carafe with an acacia wood lid. Perfect for water, juice, or iced tea. 1.2-liter capacity. Dishwasher safe (hand-wash the lid).",
    shortDescription: "Hand-blown glass carafe with acacia wood lid, 1.2 L.",
    price: 35.00,
    thumbnail: "https://images.unsplash.com/photo-1610768803788-6c4c8b6c3e0a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1610768803788-6c4c8b6c3e0a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Halden",
    stock: 90,
    tags: ["kitchen", "glassware", "carafe"],
    newArrival: true,
    rating: 4.5,
    reviewCount: 67,
    specifications: { "Capacity": "1.2 L", "Material": "Glass + acacia wood" },
  },
  {
    name: "Velvet Throw Pillow Cover",
    slug: "velvet-throw-pillow-cover",
    sku: "HOM-PIL-009",
    description: "Plush velvet pillow cover with a hidden zipper. Sold without insert. Adds rich texture and color to any sofa or bed.",
    shortDescription: "Plush velvet pillow cover, 18x18 in, hidden zipper.",
    price: 24.00,
    thumbnail: "https://images.unsplash.com/photo-1584346524174-d6e6c5d8b3e8?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584346524174-d6e6c5d8b3e8?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Marisol",
    colors: ["Mustard", "Slate", "Burgundy", "Forest", "Cream"],
    stock: 250,
    tags: ["pillow", "decor", "velvet"],
    rating: 4.6,
    reviewCount: 145,
    specifications: { "Material": "100% polyester velvet", "Size": "18 x 18 in", "Insert": "Not included" },
  },
  {
    name: "Brass Swing-Arm Wall Sconce",
    slug: "brass-swing-arm-wall-sconce",
    sku: "HOM-SCN-010",
    description: "Adjustable brass wall sconce with a linen shade. Perfect for reading nooks or flanking a bed. Hardwired or plug-in option. Bulb not included.",
    shortDescription: "Adjustable brass swing-arm sconce with linen shade.",
    price: 129.00,
    thumbnail: "https://images.unsplash.com/photo-1517991109296-8d9b1c8e6b1c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1517991109296-8d9b1c8e6b1c?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "home-living",
    brandName: "Atelier 9",
    colors: ["Antique Brass", "Matte Black"],
    stock: 60,
    tags: ["lighting", "sconce", "decor"],
    rating: 4.4,
    reviewCount: 32,
    specifications: { "Material": "Brass + linen", "Mount": "Hardwired or plug-in", "Bulb": "E26, max 60W" },
  },

  // ---------------- BEAUTY & CARE (8) ----------------
  {
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    sku: "BTY-SER-001",
    description: "A lightweight serum with 15% vitamin C, ferulic acid, and vitamin E to brighten, even skin tone, and protect against environmental stressors. Suitable for all skin types.",
    shortDescription: "15% vitamin C serum with ferulic acid and vitamin E.",
    price: 48.00,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 200,
    tags: ["skincare", "serum", "vitamin-c"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 312,
    specifications: { "Volume": "30 ml", "Key ingredients": "15% L-AA, ferulic acid, vitamin E", "Skin type": "All" },
  },
  {
    name: "Hyaluronic Acid Hydrating Moisturizer",
    slug: "hyaluronic-acid-hydrating-moisturizer",
    sku: "BTY-MOI-002",
    description: "Oil-free gel-cream with multi-weight hyaluronic acid and ceramides for plump, hydrated skin without greasiness. Fragrance-free, non-comedogenic.",
    shortDescription: "Oil-free gel-cream with hyaluronic acid and ceramides.",
    price: 38.00,
    thumbnail: "https://images.unsplash.com/photo-1571781926291-4ba5d1b3f5c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1571781926291-4ba5d1b3f5c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 180,
    tags: ["skincare", "moisturizer", "hydration"],
    rating: 4.5,
    reviewCount: 198,
    specifications: { "Volume": "50 ml", "Key ingredients": "Hyaluronic acid, ceramides, niacinamide" },
  },
  {
    name: "Niacinamide Pore Refining Serum",
    slug: "niacinamide-pore-refining-serum",
    sku: "BTY-SER-003",
    description: "10% niacinamide + zinc serum that visibly reduces the appearance of pores and uneven tone. Lightweight and absorbs quickly. Layer under moisturizer.",
    shortDescription: "10% niacinamide + zinc serum for pores and tone.",
    price: 32.00,
    thumbnail: "https://images.unsplash.com/photo-1620916566398-39f7c1f3a4c9?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f7c1f3a4c9?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 150,
    tags: ["skincare", "serum", "niacinamide"],
    newArrival: true,
    rating: 4.5,
    reviewCount: 142,
    specifications: { "Volume": "30 ml", "Key ingredients": "10% niacinamide, 1% zinc" },
  },
  {
    name: "Mineral SPF 50 Sunscreen",
    slug: "mineral-spf-50-sunscreen",
    sku: "BTY-SPF-004",
    description: "Non-nano zinc oxide sunscreen that blends without a white cast. Reef-safe, fragrance-free, and sweat-resistant. Daily broad-spectrum protection.",
    shortDescription: "Reef-safe mineral SPF 50 with no white cast.",
    price: 28.00,
    thumbnail: "https://images.unsplash.com/photo-1556228852-4a4b5b9b3b9b?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228852-4a4b5b9b3b9b?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 220,
    tags: ["skincare", "sunscreen", "spf"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 287,
    specifications: { "Volume": "50 ml", "Active": "Non-nano zinc oxide 20%", "SPF": "50" },
  },
  {
    name: "Eau de Parfum — Amber Woods",
    slug: "eau-de-parfum-amber-woods",
    sku: "BTY-PFM-005",
    description: "A warm, sophisticated fragrance with top notes of bergamot, heart of cedarwood, and a base of amber and oud. Long-lasting and gender-neutral.",
    shortDescription: "Warm amber and oud eau de parfum, gender-neutral.",
    price: 95.00,
    thumbnail: "https://images.unsplash.com/photo-1592945403908-3c65c1b6c8d9?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1592945403908-3c65c1b6c8d9?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 90,
    tags: ["fragrance", "perfume", "amber"],
    featured: true,
    rating: 4.7,
    reviewCount: 84,
    specifications: { "Volume": "50 ml", "Concentration": "Eau de Parfum" },
  },
  {
    name: "Bamboo Soft-Bristle Toothbrush (4-Pack)",
    slug: "bamboo-soft-bristle-toothbrush-4-pack",
    sku: "BTY-TBR-006",
    description: "Biodegradable bamboo handles with soft, plant-based bristles. A simple swap that cuts plastic from your daily routine. Set of four.",
    shortDescription: "4-pack of bamboo toothbrushes with soft bristles.",
    price: 18.00,
    thumbnail: "https://images.unsplash.com/photo-1559599189-5e8c8a3c9c9a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1559599189-5e8c8a3c9c9a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 300,
    tags: ["oral-care", "bamboo", "eco"],
    rating: 4.4,
    reviewCount: 224,
    specifications: { "Set": "4 toothbrushes", "Bristles": "Soft plant-based" },
  },
  {
    name: "Beeswax Lip Balm Trio",
    slug: "beeswax-lip-balm-trio",
    sku: "BTY-LIP-007",
    description: "Three nourishing beeswax lip balms in Unscented, Peppermint, and Citrus. Made with shea butter, coconut oil, and vitamin E. Plastic-free tubes.",
    shortDescription: "3-pack beeswax lip balm in Unscented, Peppermint, Citrus.",
    price: 21.00,
    thumbnail: "https://images.unsplash.com/photo-1556228720-29d1a4b3c8e9?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-29d1a4b3c8e9?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Verde",
    stock: 250,
    tags: ["lip-care", "beeswax", "eco"],
    rating: 4.7,
    reviewCount: 168,
    specifications: { "Set": "3 balms, 4 g each", "Key ingredients": "Beeswax, shea butter, coconut oil" },
  },
  {
    name: "Beard Oil & Comb Kit",
    slug: "beard-oil-and-comb-kit",
    sku: "BTY-BRD-008",
    description: "A grooming kit with beard oil, a wooden comb, and a boar-bristle brush. Jojoba and argan oils condition hair and skin without greasiness.",
    shortDescription: "Beard oil, wooden comb, and boar-bristle brush.",
    price: 42.00,
    thumbnail: "https://images.unsplash.com/photo-1626202373052-3c8d3c0e3b8a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1626202373052-3c8d3c0e3b8a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "beauty-care",
    brandName: "Halden",
    stock: 110,
    tags: ["grooming", "beard", "men"],
    rating: 4.5,
    reviewCount: 96,
    specifications: { "Oil volume": "30 ml", "Includes": "Oil, comb, brush" },
  },

  // ---------------- SPORTS & OUTDOORS (8) ----------------
  {
    name: "Insulated Stainless Water Bottle 750ml",
    slug: "insulated-stainless-water-bottle-750ml",
    sku: "SPT-BTL-001",
    description: "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12. Powder-coated finish, leak-proof lid, and a wide mouth for ice. BPA-free.",
    shortDescription: "750ml insulated bottle, 24h cold / 12h hot.",
    price: 32.00,
    thumbnail: "https://images.unsplash.com/photo-1602142167466-2c4c8c5e9b1f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1602142167466-2c4c8c5e9b1f?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Field & Co",
    colors: ["Black", "Olive", "Sand", "Coral", "Steel"],
    stock: 320,
    tags: ["hydration", "bottle", "outdoor"],
    bestSeller: true,
    rating: 4.8,
    reviewCount: 524,
    specifications: { "Capacity": "750 ml", "Material": "18/8 stainless steel", "Insulation": "24h cold / 12h hot" },
  },
  {
    name: "Adjustable Dumbbell Set 2x24kg",
    slug: "adjustable-dumbbell-set-2x24kg",
    sku: "SPT-DBL-002",
    description: "Replaces 15 sets of weights in two compact dumbbells. Dial-a-weight system from 2.5 to 24 kg per side. Includes storage tray.",
    shortDescription: "Two adjustable dumbbells, 2.5-24 kg per side.",
    price: 449.00,
    salePrice: 399.00,
    thumbnail: "https://images.unsplash.com/photo-1583451370220-9c6c8c5e8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583451370220-9c6c8c5e8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Halden",
    stock: 35,
    tags: ["fitness", "dumbbells", "home-gym"],
    featured: true,
    rating: 4.7,
    reviewCount: 89,
    specifications: { "Range": "2.5-24 kg per side", "Increment": "2.5 kg", "Set": "2 dumbbells + tray" },
    shippingInfo: "Ships in 2-4 business days.",
  },
  {
    name: "Yoga Mat 6mm Cork Top",
    slug: "yoga-mat-6mm-cork-top",
    sku: "SPT-YGM-003",
    description: "Cork surface on a natural rubber base for grip that improves as you sweat. 6mm cushioning for joints. Includes carry strap. Eco-friendly and antimicrobial.",
    shortDescription: "Cork + rubber yoga mat with superior wet grip.",
    price: 79.00,
    thumbnail: "https://images.unsplash.com/photo-1592432698-9c5c8b3c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1592432698-9c5c8b3c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Verde",
    colors: ["Cork/Natural", "Cork/Charcoal"],
    stock: 130,
    tags: ["yoga", "fitness", "cork"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 217,
    specifications: { "Thickness": "6 mm", "Material": "Cork + natural rubber", "Dimensions": "183 x 66 cm" },
  },
  {
    name: "Camping Hammock with Straps",
    slug: "camping-hammock-with-straps",
    sku: "SPT-HAM-004",
    description: "A 400-lb capacity parachute-nylon hammock that packs to the size of a grapefruit. Includes tree-friendly straps and carabiners. Sets up in under two minutes.",
    shortDescription: "Parachute nylon hammock with straps and carabiners.",
    price: 59.00,
    thumbnail: "https://images.unsplash.com/photo-1526401366-7ab3c8b9c9a3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1526401366-7ab3c8b9c9a3?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Field & Co",
    colors: ["Olive", "Charcoal", "Rust", "Teal"],
    stock: 140,
    tags: ["camping", "hammock", "outdoor"],
    newArrival: true,
    rating: 4.7,
    reviewCount: 178,
    specifications: { "Capacity": "400 lb", "Material": "210T parachute nylon", "Includes": "Hammock + straps + carabiners" },
  },
  {
    name: "Trail Daypack 24L",
    slug: "trail-daypack-24l",
    sku: "SPT-BAK-005",
    description: "A streamlined 24-liter daypack with a ventilated back panel, hydration sleeve, and rain cover. Side pockets fit most water bottles. Built for day hikes and urban commutes.",
    shortDescription: "24L daypack with ventilated back panel and rain cover.",
    price: 89.00,
    thumbnail: "https://images.unsplash.com/photo-1556328357-9d8c8c8c8e8a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556328357-9d8c8c8c8e8a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Field & Co",
    colors: ["Slate", "Olive", "Black"],
    stock: 110,
    tags: ["backpack", "hiking", "daypack"],
    rating: 4.5,
    reviewCount: 134,
    specifications: { "Capacity": "24 L", "Material": "210D ripstop nylon", "Weight": "680 g" },
  },
  {
    name: "Resistance Band Set 5-Pack",
    slug: "resistance-band-set-5-pack",
    sku: "SPT-RST-006",
    description: "Five graduated resistance bands (10-50 lb) with cushioned handles, ankle straps, and a carry bag. A complete home gym that fits in a drawer.",
    shortDescription: "5 graduated resistance bands with handles and ankle straps.",
    price: 39.00,
    thumbnail: "https://images.unsplash.com/photo-1517438476312-3c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1517438476312-3c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Halden",
    stock: 200,
    tags: ["fitness", "bands", "home-gym"],
    rating: 4.4,
    reviewCount: 156,
    specifications: { "Set": "5 bands (10-50 lb)", "Includes": "Handles, ankle straps, door anchor, carry bag" },
  },
  {
    name: "Insulated Hiking Socks (3-Pack)",
    slug: "insulated-hiking-socks-3-pack",
    sku: "SPT-SOK-007",
    description: "Merino-blend hiking socks with cushioned heel and toe, arch support, and seamless toe closure. Mid-calf height. Three pairs per pack.",
    shortDescription: "3-pack merino-blend hiking socks, mid-calf.",
    price: 32.00,
    thumbnail: "https://images.unsplash.com/photo-1558346640-5e6c8c0c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558346640-5e6c8c0c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Field & Co",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Olive", "Natural"],
    stock: 280,
    tags: ["socks", "hiking", "merino"],
    rating: 4.7,
    reviewCount: 312,
    specifications: { "Material": "65% merino, 30% nylon, 5% elastane", "Set": "3 pairs" },
  },
  {
    name: "Foam Roller Recovery Tool",
    slug: "foam-roller-recovery-tool",
    sku: "SPT-ROL-008",
    description: "High-density EVA foam roller with a textured surface for deep-tissue massage and myofascial release. Supports up to 250 kg. 33 cm length fits in a gym bag.",
    shortDescription: "Textured EVA foam roller for recovery, 33 cm.",
    price: 29.00,
    thumbnail: "https://images.unsplash.com/photo-1517968821-3c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1517968821-3c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "sports-outdoors",
    brandName: "Halden",
    colors: ["Black", "Teal", "Charcoal"],
    stock: 180,
    tags: ["recovery", "fitness", "foam-roller"],
    rating: 4.6,
    reviewCount: 142,
    specifications: { "Material": "EVA foam", "Length": "33 cm", "Diameter": "15 cm" },
  },

  // ---------------- ACCESSORIES (10) ----------------
  {
    name: "Leather Bifold Wallet",
    slug: "leather-bifold-wallet",
    sku: "ACC-WAL-001",
    description: "Full-grain leather bifold wallet with six card slots, an ID window, and a bill compartment. Hand-finished edges and a slim profile. Ages beautifully.",
    shortDescription: "Full-grain leather bifold with 6 card slots.",
    price: 69.00,
    thumbnail: "https://images.unsplash.com/photo-1627123725985-9b3c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1627123725985-9b3c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Field & Co",
    colors: ["Tan", "Brown", "Black"],
    stock: 140,
    tags: ["wallet", "leather", "men"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 234,
    specifications: { "Material": "Full-grain leather", "Slots": "6 cards + ID + bills" },
  },
  {
    name: "Canvas & Leather Weekender Bag",
    slug: "canvas-and-leather-weekender-bag",
    sku: "ACC-BAG-002",
    description: "Waxed cotton canvas body with full-grain leather trim. Roomy main compartment, separate shoe compartment, and a luggage sleeve. Carry-on compliant.",
    shortDescription: "Waxed canvas weekender with leather trim and shoe compartment.",
    price: 189.00,
    salePrice: 149.00,
    thumbnail: "https://images.unsplash.com/photo-1547949003-9792c4c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1547949003-9792c4c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Field & Co",
    colors: ["Olive/Tan", "Black/Brown", "Navy/Tan"],
    stock: 70,
    tags: ["bag", "travel", "canvas"],
    featured: true,
    rating: 4.8,
    reviewCount: 87,
    specifications: { "Material": "Waxed canvas + full-grain leather", "Capacity": "40 L", "Dimensions": "55 x 30 x 25 cm" },
  },
  {
    name: "Aviator Sunglasses Polarized",
    slug: "aviator-sunglasses-polarized",
    sku: "ACC-GLS-003",
    description: "Polarized aviator sunglasses with a stainless-steel frame and impact-resistant lenses. 100% UVA/UVB protection. Includes case and microfiber cloth.",
    shortDescription: "Polarized aviators with stainless frame.",
    price: 79.00,
    thumbnail: "https://images.unsplash.com/photo-1572636750092-9b6c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1572636750092-9b6c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Atelier 9",
    colors: ["Gold/Brown", "Silver/Black", "Black/Green"],
    stock: 180,
    tags: ["sunglasses", "eyewear"],
    bestSeller: true,
    rating: 4.5,
    reviewCount: 198,
    specifications: { "Frame": "Stainless steel", "Lens": "Polarized, 100% UV" },
  },
  {
    name: "Minimalist Leather Watch",
    slug: "minimalist-leather-watch",
    sku: "ACC-WCH-004",
    description: "A clean, minimalist dress watch with a Swiss movement, sapphire crystal, and a 38mm brushed steel case. Italian leather strap with quick-release pins.",
    shortDescription: "38mm minimalist watch, Swiss movement, leather strap.",
    price: 219.00,
    thumbnail: "https://images.unsplash.com/photo-1524805444758-0897d764c8a3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1524805444758-0897d764c8a3?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Atelier 9",
    colors: ["Tan Strap/Silver", "Black Strap/Black", "Brown Strap/Gold"],
    stock: 60,
    tags: ["watch", "leather", "dress"],
    featured: true,
    rating: 4.6,
    reviewCount: 73,
    specifications: { "Case": "38mm stainless steel", "Crystal": "Sapphire", "Movement": "Swiss quartz", "Water rating": "3 ATM" },
  },
  {
    name: "Silk Twill Scarf",
    slug: "silk-twill-scarf",
    sku: "ACC-SCF-005",
    description: "100% silk twill scarf with a hand-rolled hem. 90x90 cm. A timeless accessory that elevates anything it's paired with.",
    shortDescription: "100% silk twill scarf, 90x90 cm, hand-rolled hem.",
    price: 89.00,
    thumbnail: "https://images.unsplash.com/photo-1604061986769-3b2d3c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1604061986769-3b2d3c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Marisol",
    colors: ["Paisley Multi", "Solid Camel", "Geometric Navy"],
    stock: 95,
    tags: ["scarf", "silk", "women"],
    rating: 4.6,
    reviewCount: 56,
    specifications: { "Material": "100% silk twill", "Size": "90 x 90 cm" },
  },
  {
    name: "Leather Card Holder",
    slug: "leather-card-holder",
    sku: "ACC-CHL-006",
    description: "A slim leather card holder with four card slots and a center pocket for cash or receipts. Perfect for nights out when you don't want a full wallet.",
    shortDescription: "Slim leather card holder, 4 slots + center pocket.",
    price: 39.00,
    thumbnail: "https://images.unsplash.com/photo-1627123725985-9b3c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1627123725985-9b3c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Field & Co",
    colors: ["Tan", "Black", "Brown", "Olive"],
    stock: 220,
    tags: ["wallet", "card-holder", "leather"],
    rating: 4.6,
    reviewCount: 145,
    specifications: { "Material": "Full-grain leather", "Slots": "4 cards + center pocket" },
  },
  {
    name: "Leather Laptop Backpack",
    slug: "leather-laptop-backpack",
    sku: "ACC-BPK-007",
    description: "A clean, structured backpack in full-grain leather with a padded 15-inch laptop sleeve, magnetic closures, and a water-resistant lining. Built for daily commutes.",
    shortDescription: "Full-grain leather backpack with 15-inch laptop sleeve.",
    price: 249.00,
    thumbnail: "https://images.unsplash.com/photo-1553062409-3ca6e0c8c8a3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1553062409-3ca6e0c8c8a3?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Atelier 9",
    colors: ["Brown", "Black"],
    stock: 50,
    tags: ["backpack", "leather", "laptop"],
    newArrival: true,
    rating: 4.7,
    reviewCount: 41,
    specifications: { "Material": "Full-grain leather", "Laptop": "Up to 15 inches", "Capacity": "20 L" },
  },
  {
    name: "Beaded Bracelet Stack",
    slug: "beaded-bracelet-stack",
    sku: "ACC-BRC-008",
    description: "A set of three beaded bracelets in natural stones — matte onyx, lava rock, and tiger's eye. Stretch cord fits most wrists. Stack or wear separately.",
    shortDescription: "3-piece beaded bracelet stack in natural stones.",
    price: 35.00,
    thumbnail: "https://images.unsplash.com/photo-1595778748d2c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1595778748d2c8c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Atelier 9",
    colors: ["Onyx/Lava/Tiger's Eye", "Howlite/Lava/Tiger's Eye"],
    stock: 160,
    tags: ["jewelry", "bracelet", "men"],
    rating: 4.4,
    reviewCount: 87,
    specifications: { "Set": "3 bracelets", "Material": "Natural stone beads", "Cord": "Stretch elastic" },
  },
  {
    name: "Cashmere Beanie",
    slug: "cashmere-beanie",
    sku: "ACC-BEA-009",
    description: "A ribbed-knit cashmere beanie that's soft, warm, and lightweight. Stretchy fit. Unisex. Pairs with everything.",
    shortDescription: "Ribbed-knit cashmere beanie, unisex.",
    price: 59.00,
    thumbnail: "https://images.unsplash.com/photo-1578796816940-7b6c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1578796816940-7b6c8c8c8a3a?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Marisol",
    colors: ["Charcoal", "Camel", "Black", "Wine", "Forest"],
    stock: 120,
    tags: ["hat", "winter", "cashmere"],
    rating: 4.7,
    reviewCount: 134,
    specifications: { "Material": "100% cashmere", "Style": "Ribbed knit" },
  },
  {
    name: "Leather Belt Full-Grain",
    slug: "leather-belt-full-grain",
    sku: "ACC-BLT-010",
    description: "A solid full-grain leather belt with a brushed brass buckle. 35mm width, single-prong. Goes with jeans or chinos. Built to outlast trends.",
    shortDescription: "35mm full-grain leather belt with brass buckle.",
    price: 65.00,
    thumbnail: "https://images.unsplash.com/photo-1553062409-3ca6e0c8c8a3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1553062409-3ca6e0c8c8a3?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "accessories",
    brandName: "Field & Co",
    sizes: ["30", "32", "34", "36", "38", "40"],
    colors: ["Tan", "Brown", "Black"],
    stock: 200,
    tags: ["belt", "leather", "men"],
    rating: 4.6,
    reviewCount: 198,
    specifications: { "Material": "Full-grain leather", "Width": "35 mm", "Buckle": "Brushed brass" },
  },
];
