// =====================================================================
// KEDI HEALTHCARE — PRODUCT SEED DATA
// ---------------------------------------------------------------------
// 50+ products across 3 KEDI categories with 7 focus-area tags.
//
// Categories:
//   1. Herbal Medicine       — traditional Chinese herbal formulas
//   2. Vitamins & Supplements — nutritional supplements & wellness
//   3. Equipment & Massagers  — health devices & massage equipment
//
// Focus Area Tags (used as product tags):
//   man-power, lady-care, immune-boosting, pain-relief,
//   vitamins-body-nourishment, disease-curative, disease-preventive
//
// To replace with the real KEDI catalog: edit this file and re-run
//   bun run scripts/seed.ts
// Prices are in NGN (Nigerian Naira) and reflect typical KEDI retail.
// =====================================================================

export type SeedProduct = {
  name: string;
  slug: string;
  sku: string;
  description: string;
  shortDescription: string;
  price: number;
  salePrice?: number | null;
  currency?: string;
  thumbnail: string;
  images: string[];
  categorySlug: string;
  brandName?: string;
  sizes?: string[];
  colors?: string[];
  stock: number;
  tags?: string[];
  featured?: boolean;
  bestSeller?: boolean;
  newArrival?: boolean;
  rating?: number;
  reviewCount?: number;
  specifications?: Record<string, string>;
  shippingInfo?: string;
};

export type SeedCategory = {
  name: string;
  slug: string;
  description: string;
  image: string;
};

export type SeedBrand = {
  name: string;
  slug: string;
};

// ---------------------------------------------------------------------
// CATEGORIES (KEDI's 3 main categories)
// ---------------------------------------------------------------------
export const categories: SeedCategory[] = [
  {
    name: "Herbal Medicine",
    slug: "herbal-medicine",
    description: "Time-tested Chinese herbal formulations that support the body's natural healing — for vitality, immunity, digestion, women's health, and overall wellness.",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Vitamins & Supplements",
    slug: "vitamins-supplements",
    description: "Daily nutritional supplements, vitamins, and mineral complexes that fill dietary gaps and support long-term health.",
    image: "https://images.unsplash.com/photo-1626716493137-b67fe9501e76?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Equipment & Massagers",
    slug: "equipment-massagers",
    description: "Massagers, therapy devices, and wellness equipment designed to relieve pain, improve circulation, and support recovery.",
    image: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
  },
];

// ---------------------------------------------------------------------
// BRANDS (KEDI is the only brand on this store — these are product lines)
// ---------------------------------------------------------------------
export const brands: SeedBrand[] = [
  { name: "KEDI Healthcare", slug: "kedi-healthcare" },
  { name: "KEDI Herbal", slug: "kedi-herbal" },
  { name: "KEDI Wellness", slug: "kedi-wellness" },
];

// ---------------------------------------------------------------------
// PRODUCTS — 56 across the 3 categories
// ---------------------------------------------------------------------
export const products: SeedProduct[] = [
  // ===================== HERBAL MEDICINE (24) =====================
  {
    name: "Reishi Herbal Capsules",
    slug: "reishi-herbal-capsules",
    sku: "KEDI-RSH-001",
    description: "Reishi (Ganoderma lucidum), known as the \"mushroom of immortality,\" has been used in Chinese herbal medicine for over 2,000 years. KEDI Reishi capsules support immune function, liver health, and overall vitality. Each bottle contains 60 capsules of premium-grade Lingzhi extract standardized for active polysaccharides.",
    shortDescription: "Premium Lingzhi (Reishi) mushroom extract for immune support and vitality.",
    price: 18500,
    salePrice: 15900,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f546?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 220,
    tags: ["immune-boosting", "disease-preventive", "bestseller"],
    featured: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 412,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredient": "Ganoderma lucidum extract", "Origin": "China" },
    shippingInfo: "Ships in 1-2 business days. Free shipping on orders above ₦50,000.",
  },
  {
    name: "Cordyceps Vitality Capsules",
    slug: "cordyceps-vitality-capsules",
    sku: "KEDI-COR-002",
    description: "Cordyceps sinensis is a prized Chinese herb traditionally used to support kidney function, respiratory health, and physical endurance. KEDI Cordyceps capsules are formulated for adults seeking natural energy, stamina, and recovery support. 60 capsules per bottle.",
    shortDescription: "Supports energy, stamina, kidney and respiratory health.",
    price: 21500,
    thumbnail: "https://images.unsplash.com/photo-1584308666744-24d5c474f546?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f546?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 180,
    tags: ["man-power", "immune-boosting", "disease-preventive"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 287,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredient": "Cordyceps sinensis", "Origin": "China" },
  },
  {
    name: "Vigor Essential (Man Power)",
    slug: "vigor-essential-man-power",
    sku: "KEDI-VIG-003",
    description: "Vigor Essential is KEDI's flagship formula for men's vitality. A synergistic blend of traditional Chinese herbs that support healthy testosterone levels, stamina, and confidence. Designed for adult men seeking natural performance support. 30 capsules per bottle.",
    shortDescription: "Men's vitality formula — supports energy, stamina, and confidence.",
    price: 24500,
    salePrice: 21500,
    thumbnail: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 150,
    tags: ["man-power", "bestseller"],
    featured: true,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 524,
    specifications: { "Form": "Capsules", "Count": "30", "Use": "Adult men", "Best taken": "After meals" },
  },
  {
    name: "Eve's Care (Lady Care)",
    slug: "eves-care-lady-care",
    sku: "KEDI-EVE-004",
    description: "Eve's Care is formulated specifically for women's wellness. A traditional herbal blend that supports hormonal balance, menstrual comfort, and overall female vitality. Made with carefully sourced Chinese herbs. 30 capsules per bottle.",
    shortDescription: "Women's wellness formula — hormonal balance and vitality.",
    price: 22500,
    thumbnail: "https://images.unsplash.com/photo-1607619056571-72d3f7a4c4c5?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1607619056571-72d3f7a4c4c5?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 165,
    tags: ["lady-care", "bestseller"],
    featured: true,
    rating: 4.8,
    reviewCount: 318,
    specifications: { "Form": "Capsules", "Count": "30", "Use": "Adult women", "Best taken": "After meals" },
  },
  {
    name: "Golden Six Capsules",
    slug: "golden-six-capsules",
    sku: "KEDI-GS-005",
    description: "Golden Six is one of KEDI's most-loved women's formulas — a balanced blend of six traditional Chinese herbs that support kidney yin, hormonal balance, and graceful aging. Particularly popular with women over 40. 60 capsules per bottle.",
    shortDescription: "Six-herb formula for women's hormonal balance and graceful aging.",
    price: 19500,
    salePrice: 16900,
    thumbnail: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 195,
    tags: ["lady-care", "disease-preventive"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 267,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adult women", "Herbs": "Six synergistic formula" },
  },
  {
    name: "Gastrifort (Stomach Care)",
    slug: "gastrifort-stomach-care",
    sku: "KEDI-GAS-006",
    description: "Gastrifort is a soothing herbal formula that supports healthy digestion and stomach comfort. Made with traditional Chinese herbs known for calming the digestive tract. Recommended for adults with occasional stomach discomfort. 60 capsules per bottle.",
    shortDescription: "Supports healthy digestion and soothes occasional stomach discomfort.",
    price: 17500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 240,
    tags: ["disease-curative", "disease-preventive"],
    rating: 4.5,
    reviewCount: 187,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults", "Best taken": "After meals" },
  },
  {
    name: "Colon Cleanser Tea",
    slug: "colon-cleanser-tea",
    sku: "KEDI-COL-007",
    description: "A gentle herbal tea blend that supports regular bowel movements and digestive comfort. Made with senna leaf, cassia seed, and other traditional herbs. Caffeine-free. 20 tea bags per pack.",
    shortDescription: "Gentle herbal tea for regular digestion and detox support.",
    price: 9500,
    thumbnail: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 320,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    rating: 4.4,
    reviewCount: 156,
    specifications: { "Form": "Tea bags", "Count": "20", "Caffeine": "Free", "Best taken": "Before bed" },
  },
  {
    name: "Constilease Capsules",
    slug: "constilease-capsules",
    sku: "KEDI-CON-008",
    description: "Constilease is KEDI's convenient capsule alternative to the Colon Cleanser tea. Same gentle herbal blend in easy-to-take capsule form for regular bowel support. 60 capsules per bottle.",
    shortDescription: "Capsule-form herbal support for regular bowel movements.",
    price: 12500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 280,
    tags: ["disease-preventive"],
    rating: 4.5,
    reviewCount: 134,
    specifications: { "Form": "Capsules", "Count": "60", "Best taken": "Before bed" },
  },
  {
    name: "Magilim Weight Management",
    slug: "magilim-weight-management",
    sku: "KEDI-MAG-009",
    description: "Magilim is a herbal formula designed to support healthy weight management when combined with sensible diet and exercise. Contains cassia seed, lotus leaf, and other herbs traditionally used for metabolic support. 60 capsules per bottle.",
    shortDescription: "Herbal support for healthy weight management.",
    price: 16500,
    salePrice: 13900,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 175,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    rating: 4.3,
    reviewCount: 198,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults", "Lifestyle": "Combine with diet & exercise" },
  },
  {
    name: "Jointeez Capsules",
    slug: "jointeez-capsules",
    sku: "KEDI-JNT-010",
    description: "Jointeez is KEDI's herbal formula for joint comfort and mobility. A traditional Chinese blend supporting healthy inflammatory response and joint flexibility. Particularly popular with adults over 50. 60 capsules per bottle.",
    shortDescription: "Herbal joint support for comfort and mobility.",
    price: 19500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 165,
    tags: ["pain-relief", "disease-curative"],
    bestSeller: true,
    rating: 4.7,
    reviewCount: 245,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults", "Best for": "Joint comfort" },
  },
  {
    name: "Menstrual Reg",
    slug: "menstrual-reg",
    sku: "KEDI-MEN-011",
    description: "Menstrual Reg is a gentle herbal formula that supports regular menstrual cycles and monthly comfort. Made with traditional Chinese herbs for women's reproductive wellness. 60 capsules per bottle.",
    shortDescription: "Herbal support for regular, comfortable menstrual cycles.",
    price: 15500,
    thumbnail: "https://images.unsplash.com/photo-1607619056571-72d3f7a4c4c5?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1607619056571-72d3f7a4c4c5?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 145,
    tags: ["lady-care"],
    rating: 4.6,
    reviewCount: 178,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adult women" },
  },
  {
    name: "Eye Beta Capsules",
    slug: "eye-beta-capsules",
    sku: "KEDI-EYE-012",
    description: "Eye Beta is formulated with herbs and nutrients traditionally used to support eye health, visual clarity, and screen-time recovery. Contains wolfberry (goji), cassia seed, and beta-carotene. 60 capsules per bottle.",
    shortDescription: "Herbal and nutrient support for eye health and clarity.",
    price: 14500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 210,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    newArrival: true,
    rating: 4.5,
    reviewCount: 89,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredients": "Wolfberry, cassia seed, beta-carotene" },
  },
  {
    name: "Haemocare Blood Tonic",
    slug: "haemocare-blood-tonic",
    sku: "KEDI-HAE-013",
    description: "Haemocare is a herbal blood tonic formulated to support healthy blood production and circulation. Made with traditional Chinese herbs long used for blood vitality. 60 capsules per bottle.",
    shortDescription: "Herbal blood tonic for healthy blood and circulation.",
    price: 16500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 185,
    tags: ["vitamins-body-nourishment", "disease-preventive"],
    rating: 4.6,
    reviewCount: 156,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults" },
  },
  {
    name: "Cardiovascular Support",
    slug: "cardiovascular-support",
    sku: "KEDI-CAR-014",
    description: "A herbal formula crafted to support cardiovascular wellness and healthy circulation. Made with traditional Chinese herbs used for heart health. Recommended as part of a heart-healthy lifestyle. 60 capsules per bottle.",
    shortDescription: "Herbal support for cardiovascular wellness and circulation.",
    price: 21500,
    salePrice: 18500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 130,
    tags: ["disease-preventive", "disease-curative"],
    featured: true,
    rating: 4.7,
    reviewCount: 134,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults" },
  },
  {
    name: "Nasal Guard Inhaler",
    slug: "nasal-guard-inhaler",
    sku: "KEDI-NSG-015",
    description: "A natural herbal inhaler that supports clear nasal passages and easy breathing. Compact and travel-friendly. Made with menthol and traditional Chinese essential oils. 1 inhaler per pack.",
    shortDescription: "Natural herbal inhaler for clear breathing on the go.",
    price: 4500,
    thumbnail: "https://images.unsplash.com/photo-1584308666744-24d5c474f546?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f546?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 410,
    tags: ["disease-curative", "pain-relief"],
    rating: 4.4,
    reviewCount: 215,
    specifications: { "Form": "Inhaler", "Size": "3 g", "Key ingredients": "Menthol, eucalyptus, herbal oils" },
  },
  {
    name: "Detox Kit (7-Day)",
    slug: "detox-kit-7-day",
    sku: "KEDI-DTX-016",
    description: "KEDI's complete 7-day herbal detox program — combines Colon Cleanser tea, Constilease capsules, and a step-by-step guide. Designed to support the body's natural elimination pathways and reset healthy habits.",
    shortDescription: "Complete 7-day herbal detox program with tea, capsules, and guide.",
    price: 28500,
    salePrice: 24500,
    thumbnail: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 95,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    newArrival: true,
    rating: 4.8,
    reviewCount: 142,
    specifications: { "Duration": "7 days", "Includes": "Tea, capsules, guide", "Use": "Adults" },
  },
  {
    name: "Stress Relief Tea",
    slug: "stress-relief-tea",
    sku: "KEDI-SRT-017",
    description: "A calming herbal tea blend with chamomile, jujube seed, and lily bulb — traditional Chinese herbs for relaxation and restful sleep. Caffeine-free. 20 tea bags per pack.",
    shortDescription: "Calming herbal tea for relaxation and restful sleep.",
    price: 8500,
    thumbnail: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 380,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    rating: 4.6,
    reviewCount: 167,
    specifications: { "Form": "Tea bags", "Count": "20", "Caffeine": "Free", "Best taken": "Evening" },
  },
  {
    name: "Liver Care Formula",
    slug: "liver-care-formula",
    sku: "KEDI-LIV-018",
    description: "A traditional Chinese herbal formula crafted to support liver health and the body's natural detoxification processes. Contains milk thistle, schisandra, and other liver-supportive herbs. 60 capsules per bottle.",
    shortDescription: "Herbal support for liver health and natural detoxification.",
    price: 18500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 155,
    tags: ["disease-preventive", "disease-curative"],
    rating: 4.5,
    reviewCount: 124,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredients": "Milk thistle, schisandra" },
  },
  {
    name: "Memory Boost Capsules",
    slug: "memory-boost-capsules",
    sku: "KEDI-MEM-019",
    description: "Memory Boost combines traditional Chinese herbs like ginkgo biloba and walnut kernel to support cognitive function, focus, and memory. Particularly valued by students and older adults. 60 capsules per bottle.",
    shortDescription: "Herbal cognitive support for focus and memory.",
    price: 16500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 175,
    tags: ["vitamins-body-nourishment", "disease-preventive"],
    newArrival: true,
    rating: 4.4,
    reviewCount: 98,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredients": "Ginkgo, walnut kernel" },
  },
  {
    name: "Sleep Well Tablets",
    slug: "sleep-well-tablets",
    sku: "KEDI-SLP-020",
    description: "Sleep Well combines traditional Chinese calming herbs to support restful sleep without grogginess. Non-habit forming. 30 tablets per bottle.",
    shortDescription: "Herbal sleep support, non-habit forming.",
    price: 13500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 220,
    tags: ["disease-preventive"],
    rating: 4.5,
    reviewCount: 132,
    specifications: { "Form": "Tablets", "Count": "30", "Best taken": "30 min before bed" },
  },
  {
    name: "Prostate Care Formula",
    slug: "prostate-care-formula",
    sku: "KEDI-PST-021",
    description: "A targeted herbal formula for men over 40 — supports prostate health and urinary comfort. Made with saw palmetto, nettle root, and traditional Chinese herbs. 60 capsules per bottle.",
    shortDescription: "Herbal prostate support for men over 40.",
    price: 21500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 125,
    tags: ["man-power", "disease-preventive"],
    rating: 4.6,
    reviewCount: 87,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adult men 40+" },
  },
  {
    name: "Diabetes Care Tea",
    slug: "diabetes-care-tea",
    sku: "KEDI-DIA-022",
    description: "A traditional herbal tea formulated to support healthy blood sugar balance as part of a balanced lifestyle. Made with bitter melon, mulberry leaf, and other herbs traditionally used for glucose support. 20 tea bags per pack.",
    shortDescription: "Herbal tea to support healthy blood sugar balance.",
    price: 11500,
    thumbnail: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 195,
    tags: ["disease-curative", "disease-preventive"],
    rating: 4.3,
    reviewCount: 156,
    specifications: { "Form": "Tea bags", "Count": "20", "Key ingredients": "Bitter melon, mulberry leaf" },
  },
  {
    name: "Hypertension Support",
    slug: "hypertension-support",
    sku: "KEDI-HYP-023",
    description: "A herbal formula crafted to support healthy blood pressure levels already within normal range, as part of a heart-healthy lifestyle. Made with traditional Chinese herbs. 60 capsules per bottle.",
    shortDescription: "Herbal support for blood pressure already in normal range.",
    price: 19500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 145,
    tags: ["disease-preventive", "disease-curative"],
    rating: 4.4,
    reviewCount: 112,
    specifications: { "Form": "Capsules", "Count": "60", "Use": "Adults" },
  },
  {
    name: "Immune Booster Capsules",
    slug: "immune-booster-capsules",
    sku: "KEDI-IMB-024",
    description: "A powerful immune-support formula combining Reishi, astragalus, and vitamin C. Designed for daily use during cold season or whenever immune resilience is needed. 60 capsules per bottle.",
    shortDescription: "Daily immune support with Reishi, astragalus & vitamin C.",
    price: 17500,
    salePrice: 14900,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "herbal-medicine",
    brandName: "KEDI Herbal",
    stock: 285,
    tags: ["immune-boosting", "disease-preventive"],
    featured: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 374,
    specifications: { "Form": "Capsules", "Count": "60", "Key ingredients": "Reishi, astragalus, vitamin C" },
  },

  // ===================== VITAMINS & SUPPLEMENTS (16) =====================
  {
    name: "Zenith Nutrition (Gold)",
    slug: "zenith-nutrition-gold",
    sku: "KEDI-ZNG-025",
    description: "Zenith Gold is KEDI's premium daily nutritional supplement — a comprehensive blend of vitamins, minerals, and antioxidants for adults. Supports energy, immunity, and overall wellness. 30 sachets per box.",
    shortDescription: "Premium daily nutrition — vitamins, minerals, and antioxidants.",
    price: 28500,
    thumbnail: "https://images.unsplash.com/photo-1626716493137-b67fe9501e76?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1626716493137-b67fe9501e76?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 165,
    tags: ["vitamins-body-nourishment", "immune-boosting", "bestseller"],
    featured: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 298,
    specifications: { "Form": "Sachets", "Count": "30", "Use": "Adults", "Best taken": "After breakfast" },
  },
  {
    name: "Zenith Nutrition (Fem)",
    slug: "zenith-nutrition-fem",
    sku: "KEDI-ZNF-026",
    description: "Zenith Fem is formulated for women's daily nutritional needs — with added iron, folic acid, and B-vitamins. Supports energy, hormonal balance, and healthy skin, hair, and nails. 30 sachets per box.",
    shortDescription: "Women's daily nutrition with iron, folate, and B-vitamins.",
    price: 28500,
    thumbnail: "https://images.unsplash.com/photo-1626716493137-b67fe9501e76?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1626716493137-b67fe9501e76?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 145,
    tags: ["lady-care", "vitamins-body-nourishment"],
    rating: 4.7,
    reviewCount: 187,
    specifications: { "Form": "Sachets", "Count": "30", "Use": "Adult women" },
  },
  {
    name: "V-Ca Effervescent Vitamin C",
    slug: "v-ca-effervescent-vitamin-c",
    sku: "KEDI-VCA-027",
    description: "V-Ca is a high-absorption effervescent vitamin C + calcium tablet. Drop in water for a refreshing daily immune-boosting drink. Orange flavor. 20 tablets per tube.",
    shortDescription: "Effervescent vitamin C + calcium for daily immune support.",
    price: 12500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 320,
    tags: ["immune-boosting", "vitamins-body-nourishment"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 256,
    specifications: { "Form": "Effervescent tablets", "Count": "20", "Flavor": "Orange", "Per tablet": "1000mg vit C + calcium" },
  },
  {
    name: "Omega-3 Fish Oil",
    slug: "omega-3-fish-oil",
    sku: "KEDI-OMG-028",
    description: "High-potency omega-3 fish oil with EPA and DHA for cardiovascular, brain, and joint health. Molecularly distilled for purity. 60 softgels per bottle.",
    shortDescription: "High-potency omega-3 EPA/DHA for heart, brain, and joints.",
    price: 15500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 245,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    rating: 4.5,
    reviewCount: 187,
    specifications: { "Form": "Softgels", "Count": "60", "EPA": "360mg", "DHA": "240mg" },
  },
  {
    name: "Calcium Plus D3",
    slug: "calcium-plus-d3",
    sku: "KEDI-CAL-029",
    description: "Calcium Plus D3 supports bone density and teeth health. Each tablet provides 600mg calcium and 400IU vitamin D3 for optimal absorption. 60 tablets per bottle.",
    shortDescription: "Bone-health formula with 600mg calcium + 400IU vitamin D3.",
    price: 11500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 290,
    tags: ["vitamins-body-nourishment", "disease-preventive"],
    rating: 4.4,
    reviewCount: 156,
    specifications: { "Form": "Tablets", "Count": "60", "Calcium": "600mg", "Vitamin D3": "400IU" },
  },
  {
    name: "Multi-Vitamin Daily",
    slug: "multi-vitamin-daily",
    sku: "KEDI-MV-030",
    description: "A complete daily multivitamin for adults — 23 essential vitamins and minerals in one tablet. Supports energy, immunity, and overall wellness. 60 tablets per bottle.",
    shortDescription: "Complete daily multivitamin with 23 essential nutrients.",
    price: 9500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 380,
    tags: ["vitamins-body-nourishment", "immune-boosting"],
    bestSeller: true,
    rating: 4.5,
    reviewCount: 312,
    specifications: { "Form": "Tablets", "Count": "60", "Nutrients": "23 vitamins & minerals" },
  },
  {
    name: "Vitamin E Complex",
    slug: "vitamin-e-complex",
    sku: "KEDI-VITE-031",
    description: "Vitamin E Complex supports skin health, antioxidant protection, and immune function. Natural d-alpha tocopherol form. 60 softgels per bottle.",
    shortDescription: "Skin and antioxidant support with natural vitamin E.",
    price: 10500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 265,
    tags: ["vitamins-body-nourishment", "immune-boosting"],
    rating: 4.4,
    reviewCount: 134,
    specifications: { "Form": "Softgels", "Count": "60", "Per serving": "400 IU natural vit E" },
  },
  {
    name: "B-Complex Energy",
    slug: "b-complex-energy",
    sku: "KEDI-BCX-032",
    description: "B-Complex Energy provides all 8 essential B-vitamins for energy production, nervous system support, and stress management. 60 tablets per bottle.",
    shortDescription: "All 8 B-vitamins for energy, stress, and nervous system.",
    price: 9500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 320,
    tags: ["vitamins-body-nourishment"],
    rating: 4.5,
    reviewCount: 178,
    specifications: { "Form": "Tablets", "Count": "60", "Contains": "B1, B2, B3, B5, B6, B7, B9, B12" },
  },
  {
    name: "Iron + Folic Acid",
    slug: "iron-folic-acid",
    sku: "KEDI-IRN-033",
    description: "Iron + Folic Acid supports healthy blood production. Particularly recommended for women of reproductive age and during pregnancy. Gentle on the stomach. 60 tablets per bottle.",
    shortDescription: "Iron and folic acid for healthy blood — gentle on stomach.",
    price: 8500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 295,
    tags: ["lady-care", "vitamins-body-nourishment"],
    rating: 4.4,
    reviewCount: 145,
    specifications: { "Form": "Tablets", "Count": "60", "Iron": "65mg", "Folic acid": "400mcg" },
  },
  {
    name: "Zinc Lozenges",
    slug: "zinc-lozenges",
    sku: "KEDI-ZNC-034",
    description: "Zinc lozenges support immune resilience and throat comfort. Pleasant honey-lemon flavor. 30 lozenges per pack.",
    shortDescription: "Honey-lemon zinc lozenges for immune and throat support.",
    price: 6500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 410,
    tags: ["immune-boosting", "disease-preventive"],
    rating: 4.3,
    reviewCount: 98,
    specifications: { "Form": "Lozenges", "Count": "30", "Flavor": "Honey-lemon", "Per lozenge": "15mg zinc" },
  },
  {
    name: "Vitamin D3 5000IU",
    slug: "vitamin-d3-5000iu",
    sku: "KEDI-VD3-035",
    description: "High-strength vitamin D3 for bone health, immune function, and mood. Especially valuable during low-sunlight months. 60 softgels per bottle.",
    shortDescription: "High-strength vitamin D3 for bones, immunity, and mood.",
    price: 9500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 340,
    tags: ["immune-boosting", "vitamins-body-nourishment"],
    newArrival: true,
    rating: 4.6,
    reviewCount: 167,
    specifications: { "Form": "Softgels", "Count": "60", "Per softgel": "5000 IU D3" },
  },
  {
    name: "Magnesium Glycinate",
    slug: "magnesium-glycinate",
    sku: "KEDI-MAG2-036",
    description: "Magnesium glycinate is a highly absorbable form of magnesium — supports muscle relaxation, sleep quality, and nervous system calm. 60 tablets per bottle.",
    shortDescription: "Highly absorbable magnesium for muscles, sleep, and calm.",
    price: 11500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 220,
    tags: ["pain-relief", "vitamins-body-nourishment"],
    newArrival: true,
    rating: 4.7,
    reviewCount: 142,
    specifications: { "Form": "Tablets", "Count": "60", "Per tablet": "400mg magnesium glycinate" },
  },
  {
    name: "Probiotic Complex",
    slug: "probiotic-complex",
    sku: "KEDI-PRO-037",
    description: "Probiotic Complex delivers 10 billion CFU from 8 strains of beneficial bacteria for gut health, digestion, and immune resilience. Delayed-release capsules survive stomach acid. 30 capsules per bottle.",
    shortDescription: "10 billion CFU, 8 strains — gut, digestion, and immune support.",
    price: 14500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 195,
    tags: ["disease-preventive", "vitamins-body-nourishment"],
    rating: 4.6,
    reviewCount: 187,
    specifications: { "Form": "Capsules", "Count": "30", "CFU": "10 billion", "Strains": "8" },
  },
  {
    name: "Collagen + Vitamin C",
    slug: "collagen-vitamin-c",
    sku: "KEDI-COL2-038",
    description: "Hydrolyzed collagen peptides with vitamin C for skin elasticity, joint comfort, and hair/health. Unflavored — mixes into coffee, smoothies, or water. 30 servings per tub.",
    shortDescription: "Hydrolyzed collagen + vitamin C for skin, joints, and hair.",
    price: 19500,
    salePrice: 16900,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 175,
    tags: ["vitamins-body-nourishment", "lady-care"],
    rating: 4.7,
    reviewCount: 213,
    specifications: { "Form": "Powder", "Servings": "30", "Per serving": "10g collagen + 60mg vit C" },
  },
  {
    name: "Kids Multivitamin Gummies",
    slug: "kids-multivitamin-gummies",
    sku: "KEDI-KID-039",
    description: "Yummy chewable gummies with 11 essential vitamins for kids ages 4+. Supports growth, immunity, and energy. No artificial colors or flavors. 60 gummies per bottle.",
    shortDescription: "11 essential vitamins in kid-friendly gummies — no artificial colors.",
    price: 8500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 285,
    tags: ["vitamins-body-nourishment", "immune-boosting"],
    rating: 4.5,
    reviewCount: 198,
    specifications: { "Form": "Gummies", "Count": "60", "Age": "4+", "Flavor": "Mixed fruit" },
  },
  {
    name: "Spirulina Superfood",
    slug: "spirulina-superfood",
    sku: "KEDI-SPR-040",
    description: "Organic spirulina powder — nature's multivitamin. Rich in protein, B12, iron, and antioxidants. Mix into smoothies or sprinkle on food. 100g per pack.",
    shortDescription: "Organic spirulina — plant protein, B12, iron, antioxidants.",
    price: 12500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "vitamins-supplements",
    brandName: "KEDI Wellness",
    stock: 215,
    tags: ["vitamins-body-nourishment", "immune-boosting"],
    rating: 4.5,
    reviewCount: 112,
    specifications: { "Form": "Powder", "Weight": "100g", "Protein": "60% by weight" },
  },

  // ===================== EQUIPMENT & MASSAGERS (16) =====================
  {
    name: "Blood Circulation Massager",
    slug: "blood-circulation-massager",
    sku: "KEDI-BCM-041",
    description: "KEDI's flagship full-body blood circulation massager uses spiral vibration to stimulate circulation, relieve muscle tension, and support overall wellness. Ideal for adults with sedentary lifestyles or age-related circulation concerns. Includes remote control.",
    shortDescription: "Full-body spiral-vibration massager for circulation and recovery.",
    price: 85000,
    salePrice: 75000,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 35,
    tags: ["pain-relief", "disease-preventive"],
    featured: true,
    bestSeller: true,
    rating: 4.7,
    reviewCount: 156,
    specifications: { "Power": "200W", "Speeds": "Multiple", "Warranty": "1 year", "Includes": "Remote control" },
    shippingInfo: "Ships in 2-4 business days. Free shipping included.",
  },
  {
    name: "Cervical Neck Massager",
    slug: "cervical-neck-massager",
    sku: "KEDI-CNM-042",
    description: "A targeted neck massager with heat therapy and multiple kneading modes. Relieves neck and shoulder tension from desk work, driving, or stress. Rechargeable and portable.",
    shortDescription: "Heated neck massager with multiple kneading modes.",
    price: 28500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 95,
    tags: ["pain-relief"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 234,
    specifications: { "Modes": "3", "Heat": "Yes (3 levels)", "Battery": "Rechargeable", "Warranty": "1 year" },
  },
  {
    name: "Foot Spa Massager",
    slug: "foot-spa-massager",
    sku: "KEDI-FSM-043",
    description: "A complete foot spa experience at home — heated water, motorized rollers, and bubbles relieve foot fatigue and support overall relaxation. Particularly valued by adults who stand all day or have circulation concerns.",
    shortDescription: "Heated foot spa with motorized rollers and bubble massage.",
    price: 55000,
    salePrice: 48500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 50,
    tags: ["pain-relief", "disease-preventive"],
    featured: true,
    rating: 4.7,
    reviewCount: 178,
    specifications: { "Heat": "Yes", "Rollers": "4 motorized", "Capacity": "5L", "Warranty": "1 year" },
  },
  {
    name: "Digital Blood Pressure Monitor",
    slug: "digital-blood-pressure-monitor",
    sku: "KEDI-BPM-044",
    description: "Clinically-accurate digital blood pressure monitor with upper-arm cuff and large LCD. Stores 90 readings for two users. Irregular heartbeat detector. Clinically validated.",
    shortDescription: "Clinically-accurate upper-arm BP monitor, 2-user memory.",
    price: 24500,
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 125,
    tags: ["disease-preventive", "disease-curative"],
    bestSeller: true,
    rating: 4.6,
    reviewCount: 287,
    specifications: { "Type": "Upper-arm", "Memory": "90 readings x 2 users", "Display": "LCD", "Power": "AA batteries / AC" },
  },
  {
    name: "Pulse Oximeter",
    slug: "pulse-oximeter",
    sku: "KEDI-POX-045",
    description: "Fingertip pulse oximeter measures blood oxygen saturation (SpO2) and pulse rate in seconds. Compact and reliable. Includes lanyard and carry case.",
    shortDescription: "Fingertip SpO2 and pulse rate monitor with carry case.",
    price: 9500,
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 210,
    tags: ["disease-preventive"],
    rating: 4.4,
    reviewCount: 156,
    specifications: { "Measurement": "SpO2 + pulse rate", "Display": "OLED", "Power": "2x AAA", "Includes": "Lanyard + case" },
  },
  {
    name: "Infrared Thermometer",
    slug: "infrared-thermometer",
    sku: "KEDI-IRT-046",
    description: "Non-contact infrared forehead thermometer — accurate reading in 1 second. Suitable for all ages. Memory stores last 32 readings. Fever alarm.",
    shortDescription: "Non-contact forehead thermometer — 1-second reading.",
    price: 11500,
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 165,
    tags: ["disease-preventive"],
    rating: 4.5,
    reviewCount: 178,
    specifications: { "Type": "Non-contact infrared", "Reading time": "1 sec", "Memory": "32 readings", "Fever alarm": "Yes" },
  },
  {
    name: "TENS Pain Relief Device",
    slug: "tens-pain-relief-device",
    sku: "KEDI-TEN-047",
    description: "TENS (Transcutaneous Electrical Nerve Stimulation) device for drug-free pain relief. 12 modes and 20 intensity levels. Includes 8 electrode pads for targeted relief of back, knee, shoulder, and neck pain.",
    shortDescription: "Drug-free TENS pain relief with 12 modes and 8 pads.",
    price: 18500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 110,
    tags: ["pain-relief"],
    rating: 4.5,
    reviewCount: 132,
    specifications: { "Modes": "12", "Intensity": "20 levels", "Pads included": "8", "Battery": "Rechargeable" },
  },
  {
    name: "Handheld Body Massager",
    slug: "handheld-body-massager",
    sku: "KEDI-HBM-048",
    description: "Lightweight handheld percussion massager with 4 interchangeable heads. Targets sore muscles in neck, back, shoulders, legs, and feet. 6 speed settings.",
    shortDescription: "Handheld percussion massager with 4 heads, 6 speeds.",
    price: 17500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 145,
    tags: ["pain-relief"],
    rating: 4.4,
    reviewCount: 167,
    specifications: { "Heads": "4", "Speeds": "6", "Power": "25W", "Warranty": "1 year" },
  },
  {
    name: "Acupuncture Pen",
    slug: "acupuncture-pen",
    sku: "KEDI-ACP-049",
    description: "Electronic acupuncture pen uses laser and electrical pulse stimulation to provide targeted relief — no needles. Designed for home use on traditional acupoints. Includes 4 interchangeable tips.",
    shortDescription: "Needle-free electronic acupuncture pen for home use.",
    price: 8500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 280,
    tags: ["pain-relief", "disease-preventive"],
    newArrival: true,
    rating: 4.2,
    reviewCount: 89,
    specifications: { "Type": "Laser + electrical pulse", "Tips": "4", "Power": "AA battery", "Display": "LCD" },
  },
  {
    name: "Eye Massager",
    slug: "eye-massager",
    sku: "KEDI-EYE2-050",
    description: "Heated eye massager with air pressure, vibration, and music. Relieves eye strain from screen time, supports restful sleep, and reduces puffiness. Bluetooth music. Foldable for travel.",
    shortDescription: "Heated eye massager with air pressure, vibration & music.",
    price: 32500,
    salePrice: 27500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 75,
    tags: ["pain-relief", "disease-preventive"],
    featured: true,
    rating: 4.6,
    reviewCount: 145,
    specifications: { "Functions": "Heat, air pressure, vibration, music", "Bluetooth": "Yes", "Battery": "Rechargeable", "Foldable": "Yes" },
  },
  {
    name: "Glucometer Kit",
    slug: "glucometer-kit",
    sku: "KEDI-GLC-051",
    description: "Complete blood glucose monitoring kit — meter, 50 test strips, 50 lancets, lancing device, and carry case. Results in 5 seconds. Large LCD with backlight.",
    shortDescription: "Complete blood glucose kit — meter, 50 strips, 50 lancets.",
    price: 16500,
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 130,
    tags: ["disease-curative", "disease-preventive"],
    rating: 4.5,
    reviewCount: 198,
    specifications: { "Includes": "Meter, 50 strips, 50 lancets, case", "Result time": "5 sec", "Memory": "500 readings" },
  },
  {
    name: "Mini Massage Gun",
    slug: "mini-massage-gun",
    sku: "KEDI-MMG-052",
    description: "Compact, portable massage gun with 4 attachments and 4 speed settings. Quiet brushless motor. Ideal for athletes and active adults. Includes USB-C charging and carry case.",
    shortDescription: "Compact percussion massage gun with 4 heads, USB-C.",
    price: 25500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 105,
    tags: ["pain-relief"],
    newArrival: true,
    rating: 4.7,
    reviewCount: 134,
    specifications: { "Heads": "4", "Speeds": "4", "Battery": "Rechargeable USB-C", "Noise": "<55dB" },
  },
  {
    name: "Heat Therapy Belt",
    slug: "heat-therapy-belt",
    sku: "KEDI-HTB-053",
    description: "Adjustable heat therapy belt for lower back pain. Three heat settings and vibration massage. USB-powered for use at home, office, or in the car. One-size-fits-all.",
    shortDescription: "Heated back belt with vibration massage — USB-powered.",
    price: 13500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 220,
    tags: ["pain-relief"],
    rating: 4.4,
    reviewCount: 156,
    specifications: { "Heat settings": "3", "Vibration": "Yes", "Power": "USB", "Size": "Adjustable" },
  },
  {
    name: "Steam Inhaler",
    slug: "steam-inhaler",
    sku: "KEDI-STI-054",
    description: "Personal steam inhaler for respiratory comfort during colds, allergies, or sinus congestion. Quick 1-minute heat-up. Includes mask and mouthpiece.",
    shortDescription: "Personal steam inhaler for respiratory comfort.",
    price: 11500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 165,
    tags: ["disease-curative"],
    rating: 4.3,
    reviewCount: 112,
    specifications: { "Heat-up": "1 minute", "Capacity": "300ml", "Includes": "Mask + mouthpiece", "Power": "AC" },
  },
  {
    name: "Compost/Hot Water Bottle",
    slug: "hot-water-bottle",
    sku: "KEDI-HWB-055",
    description: "Classic rubber hot water bottle for natural heat therapy. Eases cramps, muscle aches, and cold nights. 2L capacity. Includes soft knit cover.",
    shortDescription: "2L hot water bottle with knit cover for natural heat therapy.",
    price: 5500,
    thumbnail: "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583912267550-d6c2ac3196c1?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 320,
    tags: ["pain-relief", "lady-care"],
    rating: 4.5,
    reviewCount: 234,
    specifications: { "Capacity": "2L", "Material": "Rubber + knit cover", "Warranty": "6 months" },
  },
  {
    name: "KEDI Wellness Gift Box",
    slug: "kedi-wellness-gift-box",
    sku: "KEDI-GFT-056",
    description: "A curated gift box of KEDI's most-loved wellness products — Reishi capsules, Stress Relief tea, V-Ca effervescent, and a branded tote. Perfect for introducing friends and family to KEDI.",
    shortDescription: "Curated wellness gift box — perfect intro to KEDI.",
    price: 38500,
    salePrice: 32500,
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
    ],
    categorySlug: "equipment-massagers",
    brandName: "KEDI Healthcare",
    stock: 60,
    tags: ["immune-boosting", "vitamins-body-nourishment"],
    featured: true,
    newArrival: true,
    rating: 4.9,
    reviewCount: 87,
    specifications: { "Includes": "Reishi, Stress Relief tea, V-Ca, tote", "Packaging": "Gift box" },
    shippingInfo: "Ships in 1-2 business days with free express shipping.",
  },
];
